when@dev:
    web_profiler:
        toolbar: '%enable_symfony_toolbar%'

    framework:
        profiler:
            collect: '%enable_symfony_toolbar%'
            collect_serializer_data: true

when@test:
    framework:
        profiler: { collect: false }
