api_platform:
    title: OpenVWS Admin API
    description: Internal Admin API in the OpenVWS system.
    version: 0.1.0
    show_webby: false
    formats:
        json: ['application/json']
    error_formats:
        jsonproblem: ["application/problem+json"]
    docs_formats:
        json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        collectDenormalizationErrors: true
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    exception_to_status:
        Doctrine\ORM\NoResultException: 404
    enable_docs: true
    enable_entrypoint: false
    enable_swagger: true
    enable_swagger_ui: false
    enable_re_doc: false
    asset_package: api_platform
    use_symfony_listeners: true

    openapi:
        contact:
            name: iRealisatie
            url: https://open.minvws.nl/contact
            email: woo-platform@irealisatie.nl
