security:
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - PublicationApi\Domain\Security\PublicationApiAuthenticator

    access_control:
        - { path: ^/api, roles: ROLE_API_CLIENT }
